---
- name: Install devel libs package
  apt:
    update_cache=yes
    name={{ item }}
    state=present
  with_items:
    - build-essential
    - lsof

- name: Add java repository
  command: add-apt-repository ppa:webupd8team/java

- name: Install java package
  apt:
    update_cache: yes
    name: oracle-java8-installer
    state: latest

- name: Install java default package
  apt:
    update_cache: yes
    name: oracle-java8-set-default
    state: latest