---
- name: Install devel libs package
  apt:
    update_cache=yes
    name={{ item }}
    state=present
  with_items:
    - build-essential
    - lsof

- name: Install java package
  apt:
    update_cache: yes
    name: openjdk-11-jre-headless
    state: latest